package com.tribuo.backend.jpa;
// Generated Jun 2, 2017 9:58:33 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Categorias generated by hbm2java
 */
@Entity
@Table(name = "categorias",
        catalog = "tribuo",
        uniqueConstraints = @UniqueConstraint(columnNames = "nombre_categoria")
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Categorias implements java.io.Serializable {

    private Integer idCategoria;
    private String nombreCategoria;
    private Set<Subcategorias> subcategoriases;

    /**
     *
     */
    public Categorias() {
        this.subcategoriases = new HashSet<>(0);
    }

    /**
     *
     * @param nombreCategoria
     */
    public Categorias(String nombreCategoria) {
        this.subcategoriases = new HashSet<>(0);
        this.nombreCategoria = nombreCategoria;
    }

    /**
     *
     * @param nombreCategoria
     * @param subcategoriases
     */
    public Categorias(String nombreCategoria, Set<Subcategorias> subcategoriases) {
        this.subcategoriases = new HashSet<>(0);
        this.nombreCategoria = nombreCategoria;
        this.subcategoriases = subcategoriases;
    }

    /**
     *
     * @return
     */
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_categoria", unique = true, nullable = false)
    public Integer getIdCategoria() {
        return this.idCategoria;
    }

    /**
     *
     * @param idCategoria
     */
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }

    /**
     *
     * @return
     */
    @Column(name = "nombre_categoria", unique = true, nullable = false, length = 30)
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }

    /**
     *
     * @param nombreCategoria
     */
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }

    /**
     *
     * @return
     */
    @JsonIgnore
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "categorias")
    public Set<Subcategorias> getSubcategoriases() {
        return this.subcategoriases;
    }

    /**
     *
     * @param subcategoriases
     */
    public void setSubcategoriases(Set<Subcategorias> subcategoriases) {
        this.subcategoriases = subcategoriases;
    }

}
