package com.tribuo.backend.jpa;
// Generated Oct 28, 2017 12:35:33 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Distribuidores generated by hbm2java
 */
@Entity
@Table(name = "distribuidores",
         catalog = "tribuo",
         uniqueConstraints = @UniqueConstraint(columnNames = "nombre_distribuidor")
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Distribuidores implements java.io.Serializable {

    private int idDistribuidor;
    private Fabricantes fabricantes;
    private Marcas marcas;
    private String nombreDistribuidor;
    private Set<Sucursales> sucursaleses = new HashSet<Sucursales>(0);

    public Distribuidores() {
    }

    public Distribuidores(int idDistribuidor, Fabricantes fabricantes, Marcas marcas, String nombreDistribuidor) {
        this.idDistribuidor = idDistribuidor;
        this.fabricantes = fabricantes;
        this.marcas = marcas;
        this.nombreDistribuidor = nombreDistribuidor;
    }

    public Distribuidores(int idDistribuidor, Fabricantes fabricantes, Marcas marcas, String nombreDistribuidor, Set<Sucursales> sucursaleses) {
        this.idDistribuidor = idDistribuidor;
        this.fabricantes = fabricantes;
        this.marcas = marcas;
        this.nombreDistribuidor = nombreDistribuidor;
        this.sucursaleses = sucursaleses;
    }

    @Id

    @Column(name = "id_distribuidor", unique = true, nullable = false)
    public int getIdDistribuidor() {
        return this.idDistribuidor;
    }

    public void setIdDistribuidor(int idDistribuidor) {
        this.idDistribuidor = idDistribuidor;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "fabricante", nullable = false)
    public Fabricantes getFabricantes() {
        return this.fabricantes;
    }

    public void setFabricantes(Fabricantes fabricantes) {
        this.fabricantes = fabricantes;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "marca", nullable = false)
    public Marcas getMarcas() {
        return this.marcas;
    }

    public void setMarcas(Marcas marcas) {
        this.marcas = marcas;
    }

    @Column(name = "nombre_distribuidor", unique = true, nullable = false, length = 75)
    public String getNombreDistribuidor() {
        return this.nombreDistribuidor;
    }

    public void setNombreDistribuidor(String nombreDistribuidor) {
        this.nombreDistribuidor = nombreDistribuidor;
    }

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "ditribuidores_sucursales", catalog = "tribuo", joinColumns = {
        @JoinColumn(name = "distribuidor", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "sucursal", nullable = false, updatable = false)})
    public Set<Sucursales> getSucursaleses() {
        return this.sucursaleses;
    }

    public void setSucursaleses(Set<Sucursales> sucursaleses) {
        this.sucursaleses = sucursaleses;
    }

}
