package com.tribuo.backend.jpa;
// Generated Jun 2, 2017 9:58:33 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Fabricantes generated by hbm2java
 */
@Entity
@Table(name = "fabricantes",
        catalog = "tribuo",
        uniqueConstraints = @UniqueConstraint(columnNames = "nombre_fabricante")
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Fabricantes implements java.io.Serializable {

    private Integer idFabricante;
    private String nombreFabricante;
    private Set<Distribuidores> distribuidoreses;
    private Set<Marcas> marcases = new HashSet<>(0);
    private Set<Propietarios> propietarioses = new HashSet<>(0);

    /**
     *
     */
    public Fabricantes() {
        this.distribuidoreses = new HashSet<>(0);
    }

    /**
     *
     * @param nombreFabricante
     */
    public Fabricantes(String nombreFabricante) {
        this.distribuidoreses = new HashSet<>(0);
        this.nombreFabricante = nombreFabricante;
    }

    /**
     *
     * @param nombreFabricante
     * @param distribuidoreses
     * @param marcases
     * @param propietarioses
     */
    public Fabricantes(String nombreFabricante, Set<Distribuidores> distribuidoreses, Set<Marcas> marcases, Set<Propietarios> propietarioses) {
        this.distribuidoreses = new HashSet<>(0);
        this.nombreFabricante = nombreFabricante;
        this.distribuidoreses = distribuidoreses;
        this.marcases = marcases;
        this.propietarioses = propietarioses;
    }

    /**
     *
     * @return
     */
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_fabricante", unique = true, nullable = false)
    public Integer getIdFabricante() {
        return this.idFabricante;
    }

    /**
     *
     * @param idFabricante
     */
    public void setIdFabricante(Integer idFabricante) {
        this.idFabricante = idFabricante;
    }

    /**
     *
     * @return
     */
    @Column(name = "nombre_fabricante", unique = true, nullable = false, length = 75)
    public String getNombreFabricante() {
        return this.nombreFabricante;
    }

    /**
     *
     * @param nombreFabricante
     */
    public void setNombreFabricante(String nombreFabricante) {
        this.nombreFabricante = nombreFabricante;
    }

    /**
     *
     * @return
     */
    @JsonIgnore
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "fabricantes")
    public Set<Distribuidores> getDistribuidoreses() {
        return this.distribuidoreses;
    }

    /**
     *
     * @param distribuidoreses
     */
    public void setDistribuidoreses(Set<Distribuidores> distribuidoreses) {
        this.distribuidoreses = distribuidoreses;
    }

    /**
     *
     * @return
     */
    @JsonIgnore
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "fabricantes")
    public Set<Marcas> getMarcases() {
        return this.marcases;
    }

    /**
     *
     * @param marcases
     */
    public void setMarcases(Set<Marcas> marcases) {
        this.marcases = marcases;
    }

    /**
     *
     * @return
     */
    @JsonIgnore
    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "propietarios_fabricantes", catalog = "tribuo", joinColumns = {
        @JoinColumn(name = "fabricante", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "propietario", nullable = false, updatable = false)})
    public Set<Propietarios> getPropietarioses() {
        return this.propietarioses;
    }

    /**
     *
     * @param propietarioses
     */
    public void setPropietarioses(Set<Propietarios> propietarioses) {
        this.propietarioses = propietarioses;
    }

}
