package com.tribuo.backend.jpa;
// Generated Apr 7, 2017 11:20:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fabricantes generated by hbm2java
 */
@Entity
@Table(name="FABRICANTES"
    ,catalog="tribuo"
)
public class Fabricantes  implements java.io.Serializable {


     private int idFabricante;
     private String nombreFabricante;
     private Set<Marcas> marcases = new HashSet<Marcas>(0);

    public Fabricantes() {
    }

	
    public Fabricantes(int idFabricante, String nombreFabricante) {
        this.idFabricante = idFabricante;
        this.nombreFabricante = nombreFabricante;
    }
    public Fabricantes(int idFabricante, String nombreFabricante, Set<Marcas> marcases) {
       this.idFabricante = idFabricante;
       this.nombreFabricante = nombreFabricante;
       this.marcases = marcases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_fabricante", nullable=false)
    public int getIdFabricante() {
        return this.idFabricante;
    }
    
    public void setIdFabricante(int idFabricante) {
        this.idFabricante = idFabricante;
    }

    
    @Column(name="nombre_fabricante", unique=true, nullable=false, length=30)
    public String getNombreFabricante() {
        return this.nombreFabricante;
    }
    
    public void setNombreFabricante(String nombreFabricante) {
        this.nombreFabricante = nombreFabricante;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fabricantes")
    public Set<Marcas> getMarcases() {
        return this.marcases;
    }
    
    public void setMarcases(Set<Marcas> marcases) {
        this.marcases = marcases;
    }




}


