package com.tribuo.backend.jpa;
// Generated Apr 7, 2017 11:20:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Marcas generated by hbm2java
 */
@Entity
@Table(name="MARCAS"
    ,catalog="tribuo"
)
public class Marcas  implements java.io.Serializable {


     private int idMarca;
     private Fabricantes fabricantes;
     private String nombreMarca;
     private Set<Productos> productoses = new HashSet<Productos>(0);

    public Marcas() {
    }

	
    public Marcas(int idMarca, Fabricantes fabricantes, String nombreMarca) {
        this.idMarca = idMarca;
        this.fabricantes = fabricantes;
        this.nombreMarca = nombreMarca;
    }
    public Marcas(int idMarca, Fabricantes fabricantes, String nombreMarca, Set<Productos> productoses) {
       this.idMarca = idMarca;
       this.fabricantes = fabricantes;
       this.nombreMarca = nombreMarca;
       this.productoses = productoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_marca", nullable=false)
    public int getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(int idMarca) {
        this.idMarca = idMarca;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fabricante", nullable=false)
    public Fabricantes getFabricantes() {
        return this.fabricantes;
    }
    
    public void setFabricantes(Fabricantes fabricantes) {
        this.fabricantes = fabricantes;
    }

    
    @Column(name="nombre_marca", unique=true, nullable=false, length=30)
    public String getNombreMarca() {
        return this.nombreMarca;
    }
    
    public void setNombreMarca(String nombreMarca) {
        this.nombreMarca = nombreMarca;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="marcas")
    public Set<Productos> getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set<Productos> productoses) {
        this.productoses = productoses;
    }




}


