package com.tribuo.backend.jpa;
// Generated Mar 22, 2017 7:15:02 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Presentaciones generated by hbm2java
 */
@Entity
@Table(name = "presentaciones",
         catalog = "tribuo",
         uniqueConstraints = @UniqueConstraint(columnNames = {"cantidad", "unidad_medida"})
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})

public class Presentaciones implements java.io.Serializable {

    private int idPresentacion;
    private int cantidad;
    private String unidadMedida;
    private Set<Productos> productoses = new HashSet<Productos>(0);

    public Presentaciones() {
    }

    public Presentaciones(int idPresentacion, int cantidad, String unidadMedida) {
        this.idPresentacion = idPresentacion;
        this.cantidad = cantidad;
        this.unidadMedida = unidadMedida;
    }

    public Presentaciones(int idPresentacion, int cantidad, String unidadMedida, Set<Productos> productoses) {
        this.idPresentacion = idPresentacion;
        this.cantidad = cantidad;
        this.unidadMedida = unidadMedida;
        this.productoses = productoses;
    }

    @Id

    @Column(name = "id_presentacion", unique = true, nullable = false)
    public int getIdPresentacion() {
        return this.idPresentacion;
    }

    public void setIdPresentacion(int idPresentacion) {
        this.idPresentacion = idPresentacion;
    }

    @Column(name = "cantidad", nullable = false)
    public int getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    @Column(name = "unidad_medida", nullable = false, length = 3)
    public String getUnidadMedida() {
        return this.unidadMedida;
    }

    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "presentaciones")
    @JsonIgnore
    public Set<Productos> getProductoses() {
        return this.productoses;
    }

    public void setProductoses(Set<Productos> productoses) {
        this.productoses = productoses;
    }

}
