package com.tribuo.backend.jpa;
// Generated Oct 28, 2017 12:35:33 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductosTiendasId generated by hbm2java
 */
@Embeddable
public class ProductosTiendasId implements java.io.Serializable {

    private int sucursal;
    private int producto;

    public ProductosTiendasId() {
    }

    public ProductosTiendasId(int sucursal, int producto) {
        this.sucursal = sucursal;
        this.producto = producto;
    }

    @Column(name = "sucursal", nullable = false)
    public int getSucursal() {
        return this.sucursal;
    }

    public void setSucursal(int sucursal) {
        this.sucursal = sucursal;
    }

    @Column(name = "producto", nullable = false)
    public int getProducto() {
        return this.producto;
    }

    public void setProducto(int producto) {
        this.producto = producto;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof ProductosTiendasId)) {
            return false;
        }
        ProductosTiendasId castOther = (ProductosTiendasId) other;

        return (this.getSucursal() == castOther.getSucursal())
                && (this.getProducto() == castOther.getProducto());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getSucursal();
        result = 37 * result + this.getProducto();
        return result;
    }

}
