package com.tribuo.backend.jpa;
// Generated Mar 22, 2017 7:15:02 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductosTiendasId generated by hbm2java
 */
@Embeddable
public class ProductosTiendasId  implements java.io.Serializable {


     private int nitSucursal;
     private int idProducto;

    public ProductosTiendasId() {
    }

    public ProductosTiendasId(int nitSucursal, int idProducto) {
       this.nitSucursal = nitSucursal;
       this.idProducto = idProducto;
    }
   


    @Column(name="nit_sucursal", nullable=false)
    public int getNitSucursal() {
        return this.nitSucursal;
    }
    
    public void setNitSucursal(int nitSucursal) {
        this.nitSucursal = nitSucursal;
    }


    @Column(name="id_producto", nullable=false)
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductosTiendasId) ) return false;
		 ProductosTiendasId castOther = ( ProductosTiendasId ) other; 
         
		 return (this.getNitSucursal()==castOther.getNitSucursal())
 && (this.getIdProducto()==castOther.getIdProducto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNitSucursal();
         result = 37 * result + this.getIdProducto();
         return result;
   }   


}


