package com.tribuo.backend.jpa;
// Generated Apr 7, 2017 11:20:18 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductosTiendasId generated by hbm2java
 */
@Embeddable
public class ProductosTiendasId  implements java.io.Serializable {


     private int nitSucursal;
     private int idProducto;

    public ProductosTiendasId() {
    }

    public ProductosTiendasId(int nitSucursal, int idProducto) {
       this.nitSucursal = nitSucursal;
       this.idProducto = idProducto;
    }
   


    @Column(name="nit_sucursal", nullable=false)
    public int getNitSucursal() {
        return this.nitSucursal;
    }
    
    public void setNitSucursal(int nitSucursal) {
        this.nitSucursal = nitSucursal;
    }


    @Column(name="id_producto", nullable=false)
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }




}


