package com.tribuo.backend.jpa;
// Generated Apr 14, 2017 8:01:04 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductosTiendas generated by hbm2java
 */
@Entity
@Table(name="productos_tiendas"
    ,catalog="tribuo"
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class ProductosTiendas  implements java.io.Serializable {


     private ProductosTiendasId id;
     private Productos productos;
     private Sucursales sucursales;
     private int cantidad;
     private int precio;

    public ProductosTiendas() {
    }

    public ProductosTiendas(ProductosTiendasId id, Productos productos, Sucursales sucursales, int cantidad, int precio) {
       this.id = id;
       this.productos = productos;
       this.sucursales = sucursales;
       this.cantidad = cantidad;
       this.precio = precio;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="nitSucursal", column=@Column(name="nit_sucursal", nullable=false) ), 
        @AttributeOverride(name="idProducto", column=@Column(name="id_producto", nullable=false) ) } )
    public ProductosTiendasId getId() {
        return this.id;
    }
    
    public void setId(ProductosTiendasId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_producto", nullable=false, insertable=false, updatable=false)
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="nit_sucursal", nullable=false, insertable=false, updatable=false)
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }

    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="precio", nullable=false)
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }




}


