package com.tribuo.backend.jpa;
// Generated Jun 2, 2017 9:58:33 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Propietarios generated by hbm2java
 */
@Entity
@Table(name = "propietarios",
        catalog = "tribuo",
        uniqueConstraints = @UniqueConstraint(columnNames = "nombre_propietario")
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Propietarios implements java.io.Serializable {

    private int idPropietario;
    private String nombrePropietario;
    private Set<Fabricantes> fabricanteses;

    /**
     *
     */
    public Propietarios() {
        this.fabricanteses = new HashSet<>(0);
    }

    /**
     *
     * @param nombrePropietario
     */
    public Propietarios(String nombrePropietario) {
        this.fabricanteses = new HashSet<>(0);
        this.nombrePropietario = nombrePropietario;
    }

    /**
     *
     * @param nombrePropietario
     * @param fabricanteses
     */
    public Propietarios(String nombrePropietario, Set<Fabricantes> fabricanteses) {
        this.fabricanteses = new HashSet<>(0);
        this.nombrePropietario = nombrePropietario;
        this.fabricanteses = fabricanteses;
    }

    /**
     *
     * @return
     */
    @Id
    @Column(name = "id_propietario", unique = true, nullable = false)
    public int getIdPropietario() {
        return this.idPropietario;
    }

    /**
     *
     * @param idPropietario
     */
    public void setIdPropietario(int idPropietario) {
        this.idPropietario = idPropietario;
    }

    /**
     *
     * @return
     */
    @Column(name = "nombre_propietario", unique = true, nullable = false, length = 75)
    public String getNombrePropietario() {
        return this.nombrePropietario;
    }

    /**
     *
     * @param nombrePropietario
     */
    public void setNombrePropietario(String nombrePropietario) {
        this.nombrePropietario = nombrePropietario;
    }

    /**
     *
     * @return
     */
    @JsonIgnore
    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "propietarios_fabricantes", catalog = "tribuo", joinColumns = {
        @JoinColumn(name = "propietario", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "fabricante", nullable = false, updatable = false)})
    public Set<Fabricantes> getFabricanteses() {
        return this.fabricanteses;
    }

    /**
     *
     * @param fabricanteses
     */
    public void setFabricanteses(Set<Fabricantes> fabricanteses) {
        this.fabricanteses = fabricanteses;
    }

}
