package com.tribuo.backend.jpa;
// Generated Jun 2, 2017 9:58:33 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role",
        catalog = "tribuo",
        uniqueConstraints = @UniqueConstraint(columnNames = "role")
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Role implements java.io.Serializable {

    private Integer roleId;
    private String role;
    private Set<User> users;

    /**
     *
     */
    public Role() {
        this.users = new HashSet<>(0);
    }

    /**
     *
     * @param role
     */
    public Role(String role) {
        this.users = new HashSet<>(0);
        this.role = role;
    }

    /**
     *
     * @param role
     * @param users
     */
    public Role(String role, Set<User> users) {
        this.users = new HashSet<>(0);
        this.role = role;
        this.users = users;
    }

    /**
     *
     * @return
     */
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "role_id", unique = true, nullable = false)
    public Integer getRoleId() {
        return this.roleId;
    }

    /**
     *
     * @param roleId
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     *
     * @return
     */
    @Column(name = "role", unique = true, nullable = false, length = 20)
    public String getRole() {
        return this.role;
    }

    /**
     *
     * @param role
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     *
     * @return
     */
    @JsonIgnore
    @ManyToMany(fetch = FetchType.EAGER, mappedBy = "roles")
    public Set<User> getUsers() {
        return this.users;
    }

    /**
     *
     * @param users
     */
    public void setUsers(Set<User> users) {
        this.users = users;
    }

}
