package com.tribuo.backend.jpa;
// Generated Jun 2, 2017 9:58:33 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Subcategorias generated by hbm2java
 */
@Entity
@Table(name = "subcategorias",
        catalog = "tribuo",
        uniqueConstraints = @UniqueConstraint(columnNames = {"categoria", "nombre_subcategoria"})
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Subcategorias implements java.io.Serializable {

    private Integer idSubcategoria;
    private Categorias categorias;
    private String nombreSubcategoria;
    private Set<Especificos> especificoses;

    /**
     *
     */
    public Subcategorias() {
        this.especificoses = new HashSet<>(0);
    }

    /**
     *
     * @param categorias
     * @param nombreSubcategoria
     */
    public Subcategorias(Categorias categorias, String nombreSubcategoria) {
        this.especificoses = new HashSet<>(0);
        this.categorias = categorias;
        this.nombreSubcategoria = nombreSubcategoria;
    }

    /**
     *
     * @param categorias
     * @param nombreSubcategoria
     * @param especificoses
     */
    public Subcategorias(Categorias categorias, String nombreSubcategoria, Set<Especificos> especificoses) {
        this.especificoses = new HashSet<>(0);
        this.categorias = categorias;
        this.nombreSubcategoria = nombreSubcategoria;
        this.especificoses = especificoses;
    }

    /**
     *
     * @return
     */
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_subcategoria", unique = true, nullable = false)
    public Integer getIdSubcategoria() {
        return this.idSubcategoria;
    }

    /**
     *
     * @param idSubcategoria
     */
    public void setIdSubcategoria(Integer idSubcategoria) {
        this.idSubcategoria = idSubcategoria;
    }

    /**
     *
     * @return
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "categoria", nullable = false)
    public Categorias getCategorias() {
        return this.categorias;
    }

    /**
     *
     * @param categorias
     */
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }

    /**
     *
     * @return
     */
    @Column(name = "nombre_subcategoria", nullable = false, length = 30)
    public String getNombreSubcategoria() {
        return this.nombreSubcategoria;
    }

    /**
     *
     * @param nombreSubcategoria
     */
    public void setNombreSubcategoria(String nombreSubcategoria) {
        this.nombreSubcategoria = nombreSubcategoria;
    }

    /**
     *
     * @return
     */
    @JsonIgnore
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "subcategorias")
    public Set<Especificos> getEspecificoses() {
        return this.especificoses;
    }

    /**
     *
     * @param especificoses
     */
    public void setEspecificoses(Set<Especificos> especificoses) {
        this.especificoses = especificoses;
    }

}
