package com.tribuo.backend.jpa;
// Generated Mar 22, 2017 7:15:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Sucursales generated by hbm2java
 */
@Entity
@Table(name="sucursales"
    ,catalog="tribuo"
)
public class Sucursales  implements java.io.Serializable {


     private int nit;
     private Tiendas tiendas;
     private int direccion;
     private String ciudad;
     private Set<Ventas> ventases = new HashSet<Ventas>(0);
     private Set<ProductosTiendas> productosTiendases = new HashSet<ProductosTiendas>(0);
     private Set<Compras> comprases = new HashSet<Compras>(0);

    public Sucursales() {
    }

	
    public Sucursales(Tiendas tiendas, int direccion, String ciudad) {
        this.tiendas = tiendas;
        this.direccion = direccion;
        this.ciudad = ciudad;
    }
    public Sucursales(Tiendas tiendas, int direccion, String ciudad, Set<Ventas> ventases, Set<ProductosTiendas> productosTiendases, Set<Compras> comprases) {
       this.tiendas = tiendas;
       this.direccion = direccion;
       this.ciudad = ciudad;
       this.ventases = ventases;
       this.productosTiendases = productosTiendases;
       this.comprases = comprases;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="tiendas"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="nit", unique=true, nullable=false)
    public int getNit() {
        return this.nit;
    }
    
    public void setNit(int nit) {
        this.nit = nit;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Tiendas getTiendas() {
        return this.tiendas;
    }
    
    public void setTiendas(Tiendas tiendas) {
        this.tiendas = tiendas;
    }

    
    @Column(name="direccion", nullable=false)
    public int getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(int direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="ciudad", nullable=false, length=30)
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sucursales")
    public Set<Ventas> getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set<Ventas> ventases) {
        this.ventases = ventases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sucursales")
    public Set<ProductosTiendas> getProductosTiendases() {
        return this.productosTiendases;
    }
    
    public void setProductosTiendases(Set<ProductosTiendas> productosTiendases) {
        this.productosTiendases = productosTiendases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sucursales")
    public Set<Compras> getComprases() {
        return this.comprases;
    }
    
    public void setComprases(Set<Compras> comprases) {
        this.comprases = comprases;
    }




}


