package com.tribuo.backend.jpa;
// Generated Apr 7, 2017 11:20:18 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Tiendas generated by hbm2java
 */
@Entity
@Table(name="TIENDAS"
    ,catalog="tribuo"
)
public class Tiendas  implements java.io.Serializable {


     private int nit;
     private Usuarios usuarios;
     private Integer cedula;
     private String razonSocial;
     private Sucursales sucursales;

    public Tiendas() {
    }

	
    public Tiendas(int nit, Usuarios usuarios, String razonSocial) {
        this.nit = nit;
        this.usuarios = usuarios;
        this.razonSocial = razonSocial;
    }
    public Tiendas(int nit, Usuarios usuarios, Integer cedula, String razonSocial, Sucursales sucursales) {
       this.nit = nit;
       this.usuarios = usuarios;
       this.cedula = cedula;
       this.razonSocial = razonSocial;
       this.sucursales = sucursales;
    }
   
     @Id 

    
    @Column(name="nit", nullable=false)
    public int getNit() {
        return this.nit;
    }
    
    public void setNit(int nit) {
        this.nit = nit;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="propietario", nullable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    
    @Column(name="cedula", unique=true)
    public Integer getCedula() {
        return this.cedula;
    }
    
    public void setCedula(Integer cedula) {
        this.cedula = cedula;
    }

    
    @Column(name="razon_social", unique=true, nullable=false, length=30)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

@OneToOne(fetch=FetchType.EAGER, mappedBy="tiendas")
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }




}


