package com.tribuo.backend.jpa;
// Generated Jun 2, 2017 9:58:33 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tiendas generated by hbm2java
 */
@Entity
@Table(name = "tiendas",
        catalog = "tribuo",
        uniqueConstraints = {
            @UniqueConstraint(columnNames = "cedula")
            , @UniqueConstraint(columnNames = "razon_social")}
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Tiendas implements java.io.Serializable {

    private Integer idTienda;
    private User user;
    private Integer nit;
    private int cedula;
    private String razonSocial;
    private Set<Sucursales> sucursaleses;

    /**
     *
     */
    public Tiendas() {
        this.sucursaleses = new HashSet<>(0);
    }

    /**
     *
     * @param user
     * @param cedula
     * @param razonSocial
     */
    public Tiendas(User user, int cedula, String razonSocial) {
        this.sucursaleses = new HashSet<>(0);
        this.user = user;
        this.cedula = cedula;
        this.razonSocial = razonSocial;
    }

    /**
     *
     * @param user
     * @param nit
     * @param cedula
     * @param razonSocial
     * @param sucursaleses
     */
    public Tiendas(User user, Integer nit, int cedula, String razonSocial, Set<Sucursales> sucursaleses) {
        this.sucursaleses = new HashSet<>(0);
        this.user = user;
        this.nit = nit;
        this.cedula = cedula;
        this.razonSocial = razonSocial;
        this.sucursaleses = sucursaleses;
    }

    /**
     *
     * @return
     */
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_tienda", unique = true, nullable = false)
    public Integer getIdTienda() {
        return this.idTienda;
    }

    /**
     *
     * @param idTienda
     */
    public void setIdTienda(Integer idTienda) {
        this.idTienda = idTienda;
    }

    /**
     *
     * @return
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "propietario", nullable = false)
    public User getUser() {
        return this.user;
    }

    /**
     *
     * @param user
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     *
     * @return
     */
    @Column(name = "nit")
    public Integer getNit() {
        return this.nit;
    }

    /**
     *
     * @param nit
     */
    public void setNit(Integer nit) {
        this.nit = nit;
    }

    /**
     *
     * @return
     */
    @Column(name = "cedula", unique = true, nullable = false)
    public int getCedula() {
        return this.cedula;
    }

    /**
     *
     * @param cedula
     */
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }

    /**
     *
     * @return
     */
    @Column(name = "razon_social", unique = true, nullable = false, length = 75)
    public String getRazonSocial() {
        return this.razonSocial;
    }

    /**
     *
     * @param razonSocial
     */
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    /**
     *
     * @return
     */
    @JsonIgnore
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "tiendas")
    public Set<Sucursales> getSucursaleses() {
        return this.sucursaleses;
    }

    /**
     *
     * @param sucursaleses
     */
    public void setSucursaleses(Set<Sucursales> sucursaleses) {
        this.sucursaleses = sucursaleses;
    }

}
