package com.tribuo.backend.jpa;
// Generated Mar 22, 2017 7:15:02 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ventas generated by hbm2java
 */
@Entity
@Table(name = "ventas",
         catalog = "tribuo"
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Ventas implements java.io.Serializable {

    private Integer idVenta;
    private Productos productos;
    private Sucursales sucursales;
    private int cantidad;
    private Date fecha;

    public Ventas() {
    }

    public Ventas(Productos productos, Sucursales sucursales, int cantidad, Date fecha) {
        this.productos = productos;
        this.sucursales = sucursales;
        this.cantidad = cantidad;
        this.fecha = fecha;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_venta", unique = true, nullable = false)
    public Integer getIdVenta() {
        return this.idVenta;
    }

    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_producto", nullable = false)
    public Productos getProductos() {
        return this.productos;
    }

    public void setProductos(Productos productos) {
        this.productos = productos;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "nit_sucursal", nullable = false)
    public Sucursales getSucursales() {
        return this.sucursales;
    }

    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }

    @Column(name = "cantidad", nullable = false)
    public int getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha", nullable = false, length = 10)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

}
